package model;

public enum EditType {
	CREATE_POLISH,
	READ_POLISH,
	UPDATE_POLISH,
	DELETE_POLISH,
	CREATE_ENGLISH,
	READ_ENGLISH,
	UPDATE_ENGLISH,
	DELETE_ENGLISH,
	GET_ALL_POLISH,
	GET_ALL_ENGLISH,
	GET_ALL_POLISH_LIKE,
	GET_ALL_ENGLISH_LIKE
}
